# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/v2

# 订阅链接
- type: clash
  options:
    url: https://suo.yt/pwH09is
# 订阅链接
- type: subscribe
  options:
    url: https://suo.yt/R6B3O7c
# 订阅链接
- type: subscribe
  options:
    url: https://www.cxkv2.xyz/link/MG82HFZoTlURflnL?mu=2

# 订阅链接
- type: subscribe
  options:
    url: https://bigairport.icu/api/v1/client/subscribe?token=7405c4f810cfd0787e1f0319ceca17ba
# 订阅链接
- type: subscribe
  options:
    url: https://suo.yt/svNO2vQ
    
    
    
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml

# 某个网站抓取
- type: web-freessrxyz
  options:
