# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/v2
    
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/ssr
    
- type: subscribe
  options:
    url: https://proxypoolss.tk/clash/proxies

# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://drive.proxypoolv2.tk/node_v2.txt
