# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/v2
    
# 订阅链接
- type: subscribe
  options:
    url: https://losadhwselfff2332dasd.xyz/link/BqD7MpaLWs6bOuu5?sub=1
# 订阅链接
- type: subscribe
  options:
    url: https://losadhwselfff2332dasd.xyz/link/5iN7vx435cwhpAV2?sub=1
# 订阅链接
- type: subscribe
  options:
    url: https://losadhwselfff2332dasd.xyz/link/llArk3e7tOMMFh8A?sub=1
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/ssr
# 订阅链接
- type: subscribe
  options:
    url: https://link.coolgay.icu/link/0Ylei6p2f4QgpLbE?sub=1&extend=1

# 订阅链接
- type: subscribe
  options:
    url: https://iwxf.netlify.app

# 订阅链接
- type: clash
  options:
    url: https://suo.yt/VUIZ7i0
    
# 订阅链接
- type: subscribe
  options:
    url: https://sub.qaq.wtf/


# 订阅链接
- type: subscribe
  options:
    url: http://proxypool.turinglabs.net/upload/daily/v2ray
    
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://winxray.com/%E5%85%8D%E8%B4%B9%E8%8A%82%E7%82%B9
    
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://free.v2x-nav.ml/
# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml
    

# clash格式订阅链接
- type: clash
  options:
    url: https://proxypoolss.tk/clash/proxies?speed=15,30&type=ss,ssr,vmess,trojan
    
# clash格式订阅链接
- type: clash
  options:
    url: https://suo.yt/3JY7ajS
    
    
# 订阅链接
- type: subscribe
  options:
    url: https://suo.yt/FCm78h8
    
# 订阅链接
- type: subscribe
  options:
    url: https://sspool.herokuapp.com/trojan/sub
# clash格式订阅链接
- type: clash
  options:
    url: https://suo.yt/eIBexxY

# clash格式订阅链接
- type: clash
  options:
    url: https://proxypool.ga/clash/proxies?type=ss,vmess,ssr,trojan
 
# 某个网站抓取
- type: web-freessrxyz
  options:
