# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/v2
    
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/ssr
    
- type: clash
  options:
    url: https://proxypoolss.tk/clash/proxies?filter=1

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

- type: clash
  options:
    url: https://proxypoolss.tk/clash/proxies?c=HK,TW,SG&speed=15,30

# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://drive.proxypoolv2.tk/node_v2.txt

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://t.me/s/sharecentre
