# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/v2

# 订阅链接
- type: clash
  options:
    url: https://suo.yt/VUIZ7i0
    
# 订阅链接
- type: subscribe
  options:
    url: https://sub.qaq.wtf/


# 订阅链接
- type: subscribe
  options:
    url: http://proxypool.turinglabs.net/upload/daily/v2ray
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://free.v2x-nav.ml/
# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml
    

# clash格式订阅链接
- type: clash
  options:
    url: https://proxypoolss.tk/clash/proxies?c=CN,HK,TW,SG,JP,US&speed=15,30&type=ss,vmess,ssr,trojan

# clash格式订阅链接
- type: clash
  options:
    url: https://proxypool.ga/clash/proxies?type=ss,ssr,vmess
 
# 某个网站抓取
- type: web-freessrxyz
  options:
